### ISSUE TITLE
Tooltip overlaying equipment selection on Android

### ISSUE THREAD

**Issue by TimoDeus** [mythridium/combat-simulator#11]
It's me again, sorry! Keep up the good work, you are awesome!

**Describe the bug**
On Android (Beta program) it's really hard to select equipment because the tooltip is above everything else. I don't have a way to dismiss the tooltip and can't see what items are underneath. If I click/tap the tooltip, it selects the item underneath that I couldn't even see before.

**To Reproduce**
Open combat simulator and try to change equipment on Android.

**Expected behavior**
A click/tap on the tooltip should close it, instead of selecting the item underneath.

**Screenshots**
![Screenshot_20230915-134134](https://github.com/mythridium/combat-simulator/assets/33004707/f127fab1-bb8b-408f-946d-6f57bd1f38a7)

**Device:**
Android Beta, CS 2.1.24, Pixel 7a

**Comment by TimoDeus** [comment]
Oww, right after writing this, I found out that a long-press will actually close it. Works for me, but not intuitive to find out.

**Comment by mythridium** [comment]
Thanks for the report, I've cleaned up how this functions on mobile.

* Long press will open the tooltip, as it did before.
* Tapping a tooltip, closes it, without passing the click through it.
* Closing the equipment popup is now a little more intelligent, it won't close if you tap on the background amongst the images, only the very bottom of the modal, and outside the modal, or if you select an item.

Let me know, but hopefully this should feel a little more intuitive.

Fixed in 7a09db1e1ef46b756b7b3373d4f3a00dcb0f9506
