### ISSUE TITLE
-X% GP from monsters returns NaN gp/h if GP multiplier is <0

### ISSUE THREAD

**Issue by BasChana** [mythridium/combat-simulator#13]
**Describe the bug**

**To Reproduce**
1. Have cartography Unhallowed Wasteland and agility 14 Freezing climb active with no positive modifers
2. Simulate something
3. Profit NaN GP

**Expected behavior**
should be 0 gp/h?

**Screenshots**
![image](https://github.com/mythridium/combat-simulator/assets/106909380/299a6117-bf21-4085-99f1-9e804cdce2c1)

**Device:**
PC/browser

**Comment by mythridium** [comment]
Thanks for the report, do you mind attaching your save file, which monster you are simming and which equipment set you are using?

![image](https://github.com/mythridium/combat-simulator/assets/132613374/f271155d-fb7b-4283-b563-03e49ad498e6)

I get negative numbers, which is still wrong and I'll look to get fixed, but couldn't get the NaN.

**Comment by BasChana** [comment]
i'm simulating Underwater City atm - bug seems most reproducible in
dungeons, but some regular enemies trigger it as well, probably something
to do with the gp value of items... or something
 [image: image.png][image: image.png]

https://melvoridle.com/save/5Sevm3Kx

**Comment by mythridium** [comment]
Thanks for reporting this, I was able to reproduce and fixed negative results being displayed as NaN.

I looked into the negative gold, and that's actually a thing in the game, if you have negative gp modifier, killing monsters will remove gold. I left this behaviour in the sim as it matches the actual game.

![image](https://github.com/mythridium/combat-simulator/assets/132613374/90aa9e4a-5ac9-402d-b17c-65a50bc5f1d9)

![image](https://github.com/mythridium/combat-simulator/assets/132613374/357d0600-4ef8-4500-aeda-1950782a6963)

![image](https://github.com/mythridium/combat-simulator/assets/132613374/5175ceb2-2ab8-4a63-bd08-4e4cec3c350c)

Fixed in 71dbe43bf416be338c5a803c8eabd8657e4838e1
