### ISSUE TITLE
the "Highest Hit Taken" value while inspecting a dungeon is wrong

### ISSUE THREAD

**Issue by BasChana** [mythridium/combat-simulator#14]
**Describe the bug**

**To Reproduce**
1. simulate a dungeon
3. Click on 'Inspect Dungeon'
4. change PlotType to "Highest Hit Taken"
6. select an enemy and read its max hit
7. Simulate the selected enemy
8. there will be a different max hit
9. press "simulate selected" again - this will resimulate the entire dungeon
10. check the same enemy to see another different max hit

**Expected behavior**
should display appropriate max hits for each monster

**Screenshots**
![image](https://github.com/mythridium/combat-simulator/assets/106909380/e470147d-1bfe-45ad-a8d7-de0818c8926a)
![image](https://github.com/mythridium/combat-simulator/assets/106909380/6141754c-29b2-4e94-ae72-62383c70e8c4)

**Comment by mythridium** [comment]
Thanks for reporting this, I've released a fix for this.

The problem was that while simming an individual dungeon monster, the game was incrementing the monsters to kill, so you were actually progressing through the dungeon.

I've fixed this so now it just stays on the one monster when simming for the individual monster.

Fixed in 71dbe43bf416be338c5a803c8eabd8657e4838e1
