### ISSUE TITLE
Trickery Chest is missing from the drop items list

### ISSUE THREAD

**Issue by Vazkii** [mythridium/combat-simulator#17]
**Describe the bug**
![image](https://github.com/mythridium/combat-simulator/assets/1794735/b1babeef-4f2f-4e6f-a612-d71842b25cce)

**To Reproduce**
Search for Trickery Chest in Drop Chance Options.

**Device:**
Browser, Vivaldi

**Save**
[melvoridlesave_Vazkii_10-9-2023_12900PM.txt](https://github.com/mythridium/combat-simulator/files/12846011/melvoridlesave_Vazkii_10-9-2023_12900PM.txt)

**Mod List**
[Myth] Combat Simulator
SEMI Core
Floating Items
Show Skill Modifiers
Item Uses
Shop Item Owned Indicator
ETA
AutoSort
Real Quick Equip
Combat Indicators
Kills in Combat
One Click Farming
Quick Equip Manager
Notifications
SEMI Drop Chances
Reveal Unlocks
Better Offline Recap
Show Item Sources And Uses
Bank Tab Values
Tiny Passive Icons
Forgot My Hat
Show Locked Astrology Modifiers
Reveal Cartography Map
Revelio
Show Crit Stats
Right Click Equip Menu

**Comment by mythridium** [comment]
Thanks for the bug report. Some dungeons add loot to the boss monster and other dungeons have a specific `rewards` property. The sim did not account for the `rewards` property.

I also fixed some bugs in the area, you should see all items from dungeon chests and the drop chance calculates as if you open the chests

Fixed in aadb25bf9e869ddbf59d09fa7a8ac3560dfd4519
