### ISSUE TITLE
user defined modifiers and attack styles

### ISSUE THREAD

**Issue by nadamondi** [mythridium/combat-simulator#18]
hi thank you for all the work and updates! i dont think its actually a bug but some attack styles (modded) are missing from the dropdown, would it possible to include these? currently it doesn't seem to recognize any other than the default but the mod has stuff from other mods.

a feature request: a typeahead search input bar for all the modifiers in game where users can add modifiers to add to the sim. not sure but i hope its as simple as it sounds, i think there'd be a lot of potential

**Comment by mythridium** [comment]
Thanks for the feedback. Currently, the way the simulator is written is that the interface pulls data from the game directly, but the simulator itself needs very custom work to get any modded data pushed into it.

This can result in things such as mod items showing in the ui, but when actually simulating, these slots will be empty as the item doesn't exist in the simulator.

I'm currently working on re-writing the entire mod for v3, and one of the things I'm trying to resolve is improved mod support. I've already got all modifiers added from mods, and data packages pushed into the simulator. There are still more challenges to resolve in this area, and one of my thoughts I haven't yet explored is exposing an api for mod authors to hook into that the simulator can safely handle custom mod interactions that are more advanced in nature.

Unfortunately, re-writing the mod is going to take some time, so in the short term, this won't be resolved, but I definitely want to improve this for v3. Can't confirm the extent of this just yet, as some things may not be feasible.

**Comment by mythridium** [comment]
Regarding the user defined modifiers, I'm assuming you aren't referring to custom modifiers, but adding any existing modifier in the game to the sim, like adding 500% increased gp from no source.

I'm a little hesitant to allow this since the simulator expects things to fall within the bounds of the game, so this may end up causing issues for people down the road and also increase code maintenance.

Do you mind outlining what you are trying to achieve with this, is it to supplement modifiers added from mods that aren't being pushed into the sim, or some other reason?

**Comment by mythridium** [comment]
I'm going to close this issue now that v3 is out.

Basic modding support has been added and mods can opt in to push data into combat sim if they add it via the json or data builders.

The game has changed a lot as well. Feel free to open a new issue if you need. Thanks again.
