### ISSUE TITLE
Dropdowns not working on Android

### ISSUE THREAD

**Issue by TimoDeus** [mythridium/combat-simulator#4]
The dropdowns to switch combat styles or select XP/hour, XP/day etc. are not working in the Android Beta app.
Upon tap it gains focus, but no selection shows up.

I'm using Android Beta App, Version 1.2 ?7651 and combat simulator 2.14

**Comment by mythridium** [comment]
Thanks so much for reporting this, so this looks like the android app that melvor idle uses does not support standard select html elements. The app is meant to open the native device select.

I've reported this to the developer of the game, however if they decide to not fix this I'll take a look at this, I would need to write a custom dropdown element, which is tedious, but doable.

**Comment by mythridium** [comment]
I've replaced all the dropdowns with new ones that don't use the select elements so mobile devices will no longer use the native dropdown view.

Let me know if you run into any issues, thanks for reporting this issue!

![dropdowns](https://github.com/mythridium/combat-simulator/assets/132613374/f382f70f-6f53-45b3-956d-669a5b717947)

Fixed in 79935df40bebc04e459d4f0fd2bedfef7c11f3d2

**Comment by TimoDeus** [comment]
Works as expected, thank you so much!
