### ISSUE TITLE
3.0.79 doesn't work in custom gamemodes

### ISSUE THREAD

**Issue by MagnoliaEndysis** [mythridium/combat-simulator#45]
The newest updated (3.0.79) does not work in custom gamemodes, throws out an error. It worked fine before this update. I am using [Hardcore Adventure mod](https://mod.io/g/melvoridle/m/hardcore-adventure-mode2).

**To Reproduce**
Open save with Combat Sim and Hardcore Adventure active gamemode.

**Expected behavior**
Combat sim working normally in custom gamemode. 

**Device:**
Steam

**Save**
Shouldn't be needed as I tried on fresh save. 

**Mod List/Error**
Error loading save. Gamemode is not registered.

Error: Error loading save. Gamemode is not registered.
    at SimGame.decode (https://steam.melvoridle.com/assets/js/built/game.js?11485:421:7)
    at blob:https://steam.melvoridle.com/17c9b3e6-e717-4f9c-b3ba-f81f0e6de59d:1:684750
    at async Global.time (blob:https://steam.melvoridle.com/17c9b3e6-e717-4f9c-b3ba-f81f0e6de59d:1:101144)
    at async main_Main.load (blob:https://steam.melvoridle.com/17c9b3e6-e717-4f9c-b3ba-f81f0e6de59d:1:684140)
    at async blob:https://steam.melvoridle.com/17c9b3e6-e717-4f9c-b3ba-f81f0e6de59d:1:683532

Melvor Version: v1.3
Sim Version: 3.0.79

Mod List:
 - Hardcore Adventure Mode
 - [Myth] Combat Simulator
 - Bank Tab Icons
 - Show Item Sources And Uses
 - Kills in Combat

_Save game string:
      XXX_

Sim String:

TypeError: Cannot read properties of undefined (reading 'equipment')
    at get equipment [as equipment] (https://steam.melvoridle.com/assets/js/built/player.js?11485:20:70)
    at SettingsController.export (blob:https://steam.melvoridle.com/17c9b3e6-e717-4f9c-b3ba-f81f0e6de59d:1:274252)
    at SettingsController.exportAsString (blob:https://steam.melvoridle.com/17c9b3e6-e717-4f9c-b3ba-f81f0e6de59d:1:273844)
    at Bugs.report (blob:https://steam.melvoridle.com/17c9b3e6-e717-4f9c-b3ba-f81f0e6de59d:1:265130)
    at main_Main.load (blob:https://steam.melvoridle.com/17c9b3e6-e717-4f9c-b3ba-f81f0e6de59d:1:685343)
    at async blob:https://steam.melvoridle.com/17c9b3e6-e717-4f9c-b3ba-f81f0e6de59d:1:683532

**Comment by mythridium** [comment]
Hi @MagnoliaEndysis,

Thank you for reporting this issue. Firstly, I'd like to point out that combat sim should be the first mod in your load order, this is needed so that it can correctly capture mod data.

Secondly, and more to address your issue, I had to unfortunately change some details about how gamemode data is handled in combat sim.

Prior to v3.0.79, I would blindly pull in gamemode data into combat sim, this was risky because gamemodes can rely on other modded data that also needs to be sent into combat sim. I cannot pull in this additional data automatically, so need to rely on mod authors to specifically register their mod data with combat sim, and test that it works.

In v3.0.79, I stopped pulling in custom gamemodes automatically, and they now need to register with combat sim just like all other modded data. This is to prevent other unintended errors by the mod not registering.

I'm sorry for the inconvenience this has caused, please reach out to the mod author of Hardcore Adventure mode and ask them to register with combat sim in their mod.

They can do this by calling `mod.api.mythCombatSimulator?.registerNamespace('there mods namespace');` in their setup file. This will tell combat sim to pull in their mod data and get this gamemode to function. If they require any assistance with this they are more then welcome to reach out here with an issue, or directly on discord.

In a future combat sim update I'll improve the messaging so that this case is detected and inform the user to report it with mod authors and not combat sim.

Thanks!

**Comment by MagnoliaEndysis** [comment]
Thank you,

will try communicating with the mod author. And appreciate reminding me about mod order, was switching it around just to make sure error wasn't related to that and forgot to put it back properly. 

Cheers!
