### ISSUE TITLE
Estimated death rate calculation

### ISSUE THREAD

**Issue by OslikGaming** [mythridium/combat-simulator#51]
Combat sim sometimes shows 0 estimated death rate with highest hit taken way above autoeat threshold and death quite possible. Ive added 2 screenshots with exact same setup but different sim results to illustrate issue
![No death](https://github.com/mythridium/combat-simulator/assets/26552096/9f339b95-fdaa-4ebc-9847-157691c3fef2)
![3deaths-hour](https://github.com/mythridium/combat-simulator/assets/26552096/72acc586-ae1d-4f07-a2aa-04617f0ea924)

Data from combat sim
https://gist.github.com/OslikGaming/cec03b72d01845b26d0b5d38e569ae11

**Comment by mythridium** [comment]
Hi, thank you for taking the time to report this, however this isn't a bug. The way combat sim works is that it simulates running through actual combat, just at a much faster rate than the normal game. What this result is telling you is that your chance to die is quite low, but still possible, and in the first simulation you actually got through it without dying, however in your second simulation you did end up dying.

This could be translated to something like, "you did combat for 20 hours without dying, then in the 21st hour you died" The first simulation is like the first 20 hours, and the second one is the 21st hour +. The hours are just an example, not the actual length of simulations.

My suggestion is to always run the simulation a few times, and if you see situations like this, go into the Settings tab, and increase the ticks and trials, perhaps setting both to 10,000 as an example. This will make the simulation take longer, but also runs through much more iterations so the chance of capturing the above scenario is increased because it would hit both the 20h and 21st hour situation in a single simulation. Basically a higher tick and trial count means longer sims, but more accurate, lower means faster but less chance to catch things that happen rarely, like a low chance to die.

Hope that makes sense.
